// Generated by CoffeeScript 1.6.3
window.onload = function() {
  var client;
  window.packratClient = client = new Faye.Client(location.origin + "/faye", {
    timeout: 30
  });
  client.disable("autodisconnect");
  return client.subscribe("/packrat", function(message) {
    if (message.reload) {
      console.log("reloading page");
      return location.reload();
    } else {
      console.log("reloading css...");
      return document.getElementById("packrat-css").innerHTML = message.css;
    }
  });
};
