// Generated by CoffeeScript 1.6.3
var coffeescript, path, read;

coffeescript = require('coffee-script');

read = require('fs').readFileSync;

path = require('path');

module.exports = function(packrat) {
  return function(pkg, next) {
    var files;
    if (pkg.config.scripts === void 0) {
      return next();
    }
    files = pkg.config.scripts.filter(function(file) {
      return path.extname(file) === ".coffee";
    });
    if (files.length === 0) {
      return next();
    }
    files.forEach(function(file, i) {
      var compiled, filename, realpath, str;
      realpath = pkg.path(file);
      str = read(realpath, "utf8");
      compiled = coffeescript.compile(str, {
        filename: realpath,
        bare: true
      });
      filename = file.replace(".coffee", ".js");
      pkg.addFile("scripts", filename, compiled);
      return pkg.removeFile("scripts", file);
    });
    return next();
  };
};
