// Generated by CoffeeScript 1.6.3
var path, read, stylus;

read = require('fs').readFileSync;

path = require('path');

stylus = require('stylus');

module.exports = function(packrat) {
  return function(pkg, next) {
    var files, s;
    if (pkg.config.styles === void 0) {
      return next();
    }
    files = pkg.config.styles.filter(function(file) {
      return path.extname(file) === ".styl";
    });
    s = stylus('');
    files.forEach(function(file, i) {
      s["import"](pkg.path(file));
      return pkg.removeFile("styles", file);
    });
    s.render(function(err, css) {
      var filename;
      if (err) {
        return next(err);
      }
      filename = 'styles.css';
      return pkg.addFile("styles", filename, css);
    });
    return next();
  };
};
