// Generated by CoffeeScript 1.6.3
module.exports = {
  injectAt: function(marker, str, payload) {
    var location;
    location = str.indexOf(marker);
    if (location === -1) {
      console.log('packrat: failed to locate ' + marker + ', trying </body');
      marker = '</body';
      location = str.indexOf(marker);
      if (location === -1) {
        console.log('packrat: failed to locate ' + marker + ', trying </html');
        marker = '</html';
        location = str.indexOf(marker);
      }
    }
    if (location !== -1) {
      str = str.substring(0, location) + payload + str.substring(location);
    } else {
      console.log('packrat: failed to inject');
    }
    return str;
  },
  injectHtml: function(str, css, js) {
    str = this.injectAt('</head', str, css);
    str = this.injectAt('<script', str, js);
    return str;
  }
};
